services:
  - name: mariadb:latest
    alias: db

# place project specific paths in variables to make the rest of the script more generic
variables:
  APP_FOLDER_PATH: ./src/Messger
  # TEST_FOLDER_PATH: ./tests/RestApi.Test
  # MARIADB_ROOT_PASSWORD: secret

stages:
  - build
  # - test

.dotnet-core-runner: &dotnet-core-runner
  image: mcr.microsoft.com/dotnet/sdk:6.0-focal
  tags:
    - test

.dotnet-core: &dotnet-core
  <<: *dotnet-core-runner
  before_script:
    - dotnet --version
  tags:
    - docker

build:
  <<: *dotnet-core
  stage: build
  tags:
    - docker
  script:
    - cd $APP_FOLDER_PATH
    - dotnet build

# unit-test:
#   <<: *dotnet-core
#   stage: test
#   tags:
#     - docker
#   script:
#     - cd $TEST_FOLDER_PATH
#     - dotnet test /p:CollectCoverage=true